client/.eslintrc.json, client/src/pages/demo/components/index.tsx, client/src/shared/components/Iframe/index.tsx
- [LMS-310](https://framgiaph.backlog.com/view/LMS-310)
- should have an Iframe component
- Import Iframe Component
- 'src' is the only property that is required, the rest is optional
- you can access it [here](http://localhost:3000/demo/components)
n/a
n/a
=> [feature] Iframe

client/src/pages/demo/layouts/learning.tsx, client/src/shared/icons/menu.tsx, client/src/shared/icons/next.tsx, client/src/shared/icons/previous.tsx, client/src/shared/layouts/layout-learning.tsx, client/src/shared/layouts/sidebar.tsx
=> [LAYOUTS] Layout-learning

client/src/pages/demo/components/index.tsx, client/src/shared/components/Pagination/index.tsx
[LMS-315](https://framgiaph.backlog.com/view/LMS-315)
- Able to display a functional pagination component in this [url ](http://localhost:3000/demo/components#pagination)
- Page number should also display in the url upon user interaction
- Import Pagination in the page you want it to be utilized
n/a
- To properly demonstrate page event handling you can add this code as well in the page
```
// sets up the state of the page to track user interaction
const [currentPage, setCurrentPage] = useState(2);
const handleChangePageEvent = (page: number): void => {
setCurrentPage(page);
};
```
=> [Reusable Component] Pagination

client/src/pages/demo/components/index.tsx, client/src/shared/components/TextField/index.tsx
[LMS-317](https://framgiaph.backlog.com/view/LMS-317)
> Able to create a text-field
> Able to show text-field after accessing the component in the index.tsx
cd client, npm run dev
test the component : http://localhost:3000/demo/components
location of the component: shared/components/Text-field/text-field.tsx
demo/components/index.tsx
n/a
=> [FORM] Text Field

client/src/pages/demo/components/index.tsx, client/src/shared/components/SearchBar/SearchBar.tsx
https://framgiaph.backlog.com/board/LMS?selectedIssueKey=LMS-318
Able to input strings
*cd client
*npm run dev
visit url: http://localhost:3000/demo/components
Searchbar
n/a
=> [Reusable Component] Searchbar

client/src/pages/demo/components/index.tsx, client/src/shared/components/Collapse/Collapse.tsx
https://framgiaph.backlog.com/board/LMS?selectedIssueKey=LMS-309
* should hide and show the content if the header is clicked
* should change icon from upward to downward direction (vice-versa)
cd client
npm run dev
visit url http://localhost:3000/demo/components
n/a
There is no free Draggable Icon so I used different Icon Instead
=> [CONTENTS] Collapse

client/src/pages/demo/components/index.tsx, client/src/shared/components/Button/index.tsx
[LMS-320](https://framgiaph.backlog.com/view/LMS-320)
- Be able to use button component with or without functions, and  can have any color and width using the tailwind standard
- http://localhost:3000/demo/components
- click every button, some of it have a function included (open your browser console also)
- to use, just import the Button Component, and pass a text, the rest is optional
n/a
n/a
=> [Reusable Component] Event Button

client/src/pages/demo/components/index.tsx, client/src/shared/components/Radiobutton/index.tsx
https://framgiaph.backlog.com/view/LMS-322
> Able to create radio button based on the Figma design
> Radiobutton is displayed after calling the component
test: http://localhost:3000/demo/components
component location: shared/components/Radiobutton/index.tsx
demo/components/index.tsx
n/a
=> [BUTTON] Radiobutton

client/src/shared/components/Dropdown/index.tsx
When the user clicks anywhere in the page, the dropdown component closes automatically
http://localhost:3000/demo/components#dropdown
n/a
n/a
=> [BUG FIX] Fixed dropdown Issue

client/src/pages/demo/components/index.tsx, client/src/pages/demo/layouts/navbar.tsx, client/src/shared/components/Checkbox/index.tsx, client/src/shared/components/NavLink/index.tsx, client/src/shared/components/Navbar/index.tsx, client/src/shared/components/Radiobutton/index.tsx, client/src/shared/components/SearchBar/SearchBar.tsx, client/src/shared/components/Select/index.tsx, client/src/shared/components/Table/index.tsx
[LMS-326](https://framgiaph.backlog.com/view/LMS-326)
- remove unnecessary codes
- format all files using prettier
- previous [PR](https://github.com/framgia/sph-lms/pull/20)
- /demo/component/index.tsx
- checkbox
- Navlink
- Narvbar
- Radiobutton
- SearchBar
- Select
- Table
n/a
=> [LMS-326][Reusable Component] Table-v2

client/src/pages/courses/create.tsx, client/src/shared/components/Button/index.tsx, client/src/shared/components/Footer/index.tsx
https://framgiaph.backlog.com/view/LMS-77
- Be able to see page for creating courses
- Be able to see name input field
- Be able to see description textarea field
- Be able to see footer
- Be able to see and click cancel button to redirect previous page
- Be able to see create button
- Go to http://localhost:3000/ first
- Then go to http://localhost:3000/courses/create
- Try to click cancel button
n/a
- Needed to change the button component so that the cancel button redirection would work
=> [LMS-77][FE] Create course page

api/app_sph_lms/api/urls.py, client/package-lock.json, client/package.json, client/src/pages/demo/components/index.tsx, client/src/pages/trainer/course/[id]/enrollUser.tsx, client/src/shared/components/Breadcrumbs/index.tsx, client/src/shared/components/Select/index.tsx, client/src/shared/components/Table/index.tsx, client/src/shared/hooks/useShowPerPage.ts, client/src/shared/utils/axios.ts, client/src/shared/utils/index.ts, client/src/shared/utils/interface.ts, client/src/shared/utils/toastify.ts
[LMS-333 [FE/BE] [Enroll User] Show Per Page](https://framgiaph.backlog.com/view/LMS-333)
- display the number of data base from the selected option
- fix utils file
- layout enroll user page
- Update your .env.local first
`NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api/`
- test the functionality [here](http://localhost:3000/trainer/course/21/enrollUser)
n/a
- since the data I am fetching from [jsonplaceholder](https://jsonplaceholder.typicode.com/users) is just an array of 10 objects, for better testing, you can adjust the `showPerPageOption` 's IDs, ID served as the limiter for this functionality
- I am using jsonplaceholder for the dummy data, Ill update it soon after user seeder is done
=> [LMS-333][Integration] Show Per Page

client/src/pages/trainer/course/detail/[id].tsx, client/src/shared/icons/EllipsesHorizontalIcon.tsx
[LMS-335](https://framgiaph.backlog.com/view/LMS-335)
- Able to create the layout according to Figma design 
- Accepts dynamic content
- Able to display the three dots (not functional)
http://localhost:3000/trainer/course/detail/[id]
trainer/course/detail/[id].tsx
n/a
=> [LMS-335][FE]Course Detail Header

client/package-lock.json, client/package.json, client/src/pages/demo/components/data.json, client/src/pages/demo/layouts/LearnersTab.tsx, client/src/shared/components/SelectionModal/index.tsx, client/src/shared/icons/TrashIcon.tsx
[LMS-84](https://framgiaph.backlog.com/view/LMS-84)
Selection Modal component should be created and is demonstrated with the use of a dynamic data table
1. docker-compose up
2. http://localhost:3000/demo/layouts/LearnersTab
n/a
n/a
=> [LMS-84][Frontend] Selection Modal

client/.dockerignore, client/Dockerfile, docker-compose.yml
https://framgiaph.backlog.com/view/LMS-337
- Be able to install/uninstall npm dependencies in both host and container.
- Remove previous containers and volumes
- Run `docker compose build --no-cache` to rebuild. No errors should be displayed
- Run `docker compose up`
- Install node packages via `docker exec -it lms-nextjs sh` and run `npm install`
- Install nvm for WSL first.
- Stop the containers
- Remove `client/node_modules` by running `sudo rm -rf client/node_modules`
- Use the node version the same as the container. 18.15.0. You can use nvm to update the node version.
- Run `npm install`
- If there's an error with permission, run: `sudo chmod -R 777 /client/node_modules`. Then run `npm install` again.
- To sync dependencies from container to host, npm install should be done in both …
=> [LMS-337][DOCKER] Fix client docker issues

api/Pipfile, api/Pipfile.lock, api/app/settings.py, api/app_sph_lms/api/serializers.py, api/app_sph_lms/api/urls.py, api/app_sph_lms/api/views.py
[LMS-346 [BE][API] Sign-in Page](https://framgiaph.backlog.com/view/LMS-346)
- run migration first
* Login : http://localhost:8000/api/auth/sign-in
-- test using form-data (use valid and invalid creds)
* API Health Check: http://localhost:8000/api/auth/user
-- pass Authorization : Token <token> in Header
n/a
- I am currently using Username instead of just Name since the seeder and migration for the user model is not ready yet, will update this soon.
=> [LMS-346][BE] Sign In API

client/src/pages/home/index.tsx, client/src/shared/components/Navbar/index.tsx, client/src/shared/utils/navBarList.ts
https://framgiaph.backlog.com/board/LMS?selectedIssueKey=LMS-340&assignee=417519
Created /home  for the homepage
Logout button should be visible in the navbar
Random Content should be displayed
Navbar should be sticky and must remain in the top always upon scrolling up and down 
docker compose up -d
visit url: http://localhost:3001/home
navbar component
pages/home/index.tsx
n/a
=> [LMS-340][FE][Markup] Home Page

client/src/shared/components/Avatar/index.tsx, client/src/shared/components/Navbar/index.tsx
[LMS-357](https://framgiaph.backlog.com/view/LMS-357)
1. Clear cache to remove localStorage
2. Go to http://localhost:3000/auth/sign-in
3. sign in using ( admin@gmail.com || password )
Avatar.tsx
NavBar.tsx
- You cannot access /auth/sign-in if you do not clear localStorage cache
- Please clear to gain access to sign in page for testing if hydration error still persist
=> [LMS-357][BUG FIX] Fix markup sign-in page

client/src/pages/users/[company_id]/list/index.tsx, client/src/shared/components/Pagination/index.tsx, client/src/shared/components/Table/index.tsx, client/src/shared/icons/EditIcon.tsx, client/src/shared/utils/interface.ts
[LMS-350](https://framgiaph.backlog.com/view/LMS-350)
http://localhost:3000/users/1/list
- shared/components/Table/index.tsx
- shared/components/Pagination/index.tsx
- shared/utils/interface.tsx
n/a
=> [LMS-350][FE][Markup]User List Page

api/app_sph_lms/api/serializers.py
[LMS-359 [BE][API] Sorting column](https://framgiaph.backlog.com/view/LMS-359)
- login in postman first to get a tokon
- base url
http://localhost:8000/api/user/<:company_id>
- params accepted
page = N
page_size = N
sort_by = 'id', 'email', 'first_name', 'last_name'
sort_order = desc (default ascending, dont actually need to include if not intended sort descending)
e.g http://localhost:8000/api/user/1?page_size=3&page=2&sort_by=id&sort_order=desc
- serializer
-- Company Serializer
- I used the existing class and url to make the sorting and pagination working at the same time
n/a
=> [BE][API] User List Sorting Column

client/src/pages/demo/components/index.tsx, client/src/pages/trainer/course/create.tsx, client/src/pages/trainer/course/detail/[id].tsx, client/src/sections/landing-page/NavbarSection.tsx, client/src/shared/layouts/CourseSettingTab/index.tsx
[LMS-362](https://framgiaph.backlog.com/view/LMS-362)
Sign up button should now be visible using the custom tailwindcss color
http://localhost:3000/
http://localhost:3000/trainer/course/detail/21
http://localhost:3000/trainer/course/create
http://localhost:3000/demo/components
NavbarSection.tsx
create.tsx
course - [id].tsx
demo components - index
CourseSettingTab - index
n/a
=> [LMS-362][BUG FIX] Sign up button

client/src/pages/users/[company_id]/list/index.tsx, client/src/shared/hooks/useShowUserList.ts, client/src/shared/utils/interface.ts
[LMS-352](https://framgiaph.backlog.com/view/LMS-352)
- http://localhost:3000/users/1/list
- src/pages/users/company_id/list/index.tsx
n/a
=> [LMS-352][BE][Integration]- User List

client/src/pages/demo/components/data.json, client/src/pages/demo/components/index.tsx, client/src/pages/demo/layouts/LearnersTab.tsx, client/src/pages/trainer/course/[id]/enrollUser.tsx, client/src/pages/trainer/courses/list/index.tsx, client/src/pages/users/[company_id]/list/index.tsx, client/src/shared/components/Table/index.tsx, client/src/shared/hooks/useShowUserList.ts
[LMS-360 [Integration] Sorting Column](https://framgiaph.backlog.com/view/LMS-360)
- Update User Serializer
-- Role return ID and Title
-- Status return ID and Name
- can click either first_name. last_name, and email and sort the data by that attribute
- down | up button changing on click
- show arrow only in the selected header
n/a
- FE/BE integration
- code clean up
- rebase
- I am just logging the data for now, but you can see in that log that everytime header is clicked, there is a request and proper sorting
=> [LMS-360][Integration] User List Sorting Column

client/src/shared/hooks/useAuthMiddleware.ts, client/src/shared/hooks/useAuthSignIn.ts, client/src/shared/hooks/useSignOut.ts, client/src/shared/utils/axios.ts, client/src/shared/utils/index.ts, client/src/shared/utils/localStorage.ts
[LMS-376 [INTEGRATION] Authentication Middleware](https://framgiaph.backlog.com/view/LMS-376)
- login
- edit token in local storage manually
- refresh page
- client/src/shared/hooks/useAuthMiddleware.ts
- client/src/shared/hooks/useAuthSignIn.ts
- client/src/shared/hooks/useSignOut.ts
- client/src/shared/utils/axios.ts
- client/src/shared/utils/axios.ts
n/a
=> [LMS-376][BUGFIX] Authentication Middleware

api/app_sph_lms/api/serializers.py, api/app_sph_lms/api/urls.py, api/app_sph_lms/api/views.py, client/package-lock.json, client/package.json, client/src/pages/trainer/course/create.tsx, client/src/shared/components/ReactForm/RFTextField/index.tsx, client/src/shared/components/Select/index.tsx, client/src/shared/hooks/useCreateCourse.ts, client/src/shared/utils/interface.ts
[LMS-373 [INTEGRATION] Create Course Page
](https://framgiaph.backlog.com/view/LMS-373)
Install Multi Select Component Package
`docker exec -it lms-nextjs sh`
`npm i react-multi-select-component`
http://localhost:3000/trainer/course/create
- create course
- multiselect category
- validation
-- name: required
-- description: not required, but at least 5 characters if filled out
-- select at least one category
n/a
- still need code clean up, but it is now functional
=> [LMS-373][Bugfix][Integration] Create Course Page

client/src/pages/trainer/course/[id]/enrollUser.tsx, client/src/shared/hooks/useEnrollUser.ts
https://framgiaph.backlog.com/board/LMS?selectedIssueKey=LMS-332
docker-compose up
visit url: http://localhost:3000/trainer/course/1/enrollUser
shared/hooks/useEnrollUser.ts
pages/trainer/course/[id]/enrollUser.tsx
Test pagination
n/a
=> [LMS-332][FE/BE] [Enroll User] Pagination

client/app/hooks.ts, client/app/store.ts, client/features/counter/counterSlice.ts, client/package-lock.json, client/package.json, client/src/pages/_app.tsx, client/src/pages/demo/components/index.tsx
Link: https://framgiaph.backlog.com/view/LMS-613
- docker exec -it lms-nextjs sh
- npm install
After these steps, if you get an error, please delete your `node_modules` folder in client, and run `npm install` again 
For using RTK query, please refer to the docs, you only need to create a api service and register it in store (https://redux-toolkit.js.org/tutorials/rtk-query)
https://github.com/framgia/sph-lms/assets/110364690/041c5276-1ce4-4dda-8bd7-624c8367adcd
=> LMS-613 - State management setting up

.pre-commit-config.yaml, client/.eslintrc.json
https://framgiaph.backlog.com/view/LMS-616
* fix pre-commit errors
```shell
pre-commit install
```
n/a
- create a file
- remove semicolon
n/a
n/a
=> LMS-616 Pre-commit errors hotfix

api/app/settings.py, api/app_sph_lms/api/view/course_view.py, api/app_sph_lms/fixtures/user.json, client/app/store.ts, client/services/courseAPI.ts, client/src/pages/trainer/courses/index.tsx, client/src/shared/components/Card/CourseCard/index.tsx, client/src/shared/components/Pagination/index.tsx, client/src/shared/utils/interface.ts
[LMS-597 [API/ INTEGRATION] Trainer can view a list of courses](https://framgiaph.backlog.com/view/LMS-597)
* Should have an api that returns list of all the courses
* Pagination if 12 or more items in one page
* login as admin.trainer
* go to page `http://localhost:3000/trainer/courses`
* courses page only
page 1
page 2
=> LMS-597 [API/ INTEGRATION] Trainer can view a list of courses

api/app_sph_lms/api/view/course_view.py, client/app/store.ts, client/services/courseAPI.ts, client/src/pages/trainer/courses/index.tsx, client/src/shared/components/SearchBar/SearchBar.tsx
[LMS-598 [API/Integration] Trainer can search courses](https://framgiaph.backlog.com/view/LMS-598)
- Go to `http://localhost:3000/trainer/courses`
- Type in the search input field and hit enter
- Results will be loaded. If there are none, a message will be displayed
- Clear the search input field to fetch all courses
- Courses page
- CourseCard component
- SearchBar component
[Screencast 2023-05-24 17-31-22.webm](https://github.com/framgia/sph-lms/assets/116238730/66f8dca1-342a-4baf-8ef2-052bec1a6310)
=> [LMS-598] [API/Integration] Trainer can search courses

client/src/shared/components/Avatar/index.tsx, client/src/shared/components/Navbar/index.tsx
[Navbar notification icon & profile picture fix](https://framgiaph.backlog.com/view/LMS-647)
- Login as any user
- Navbar
- Avatar
n/a
=> [LMS-647] Navbar notification icon & profile picture fix

api/app_sph_lms/api/serializer/learning_path_serializer.py, api/app_sph_lms/api/view/learning_path_view.py, client/services/learningPathAPI.ts, client/src/pages/trainer/courses/index.tsx, client/src/pages/trainer/learning-paths/index.tsx, client/src/sections/landing-page/HeroSection.tsx, client/src/sections/learning-paths/index.tsx, client/src/shared/components/Card/LearningPathCard/index.tsx, client/src/shared/components/Dropdown/SortDropdown/SortDropdown.tsx, client/src/shared/utils/interface.ts
https://framgiaph.backlog.com/view/LMS-626
- Learning Path Page
- Learning Path Card
- Learning Path API
- Learning Path Interface
- Learning Path Serializer
- Learning Path View
n/a
=> [LMS-626] [API/INTEGRATION] Trainer can view a list of LP

client/src/pages/_document.tsx, client/src/pages/auth/old/index.tsx, client/src/pages/auth/sign-in/index.tsx, client/src/shared/hooks/useAuthMiddleware.ts, client/src/shared/icons/GoogleIcon.tsx, client/src/shared/icons/SunBear.tsx, client/tailwind.config.js
https://framgiaph.backlog.com/view/LMS-640
- Sign In Page
- SunBear icon
- useAuthMiddleware
n/a
=> [LMS-640] [Markup] Sign In Page

api/app_sph_lms/api/serializer/learning_path_serializer.py, api/app_sph_lms/api/view/trainee_view.py, client/services/learningPathAPI.ts, client/services/traineeAPI.ts, client/src/shared/components/Modal/AddLearnerModal.tsx
[LMS-627 [API/Integration] Learning Path Search and Add Learners](https://framgiaph.backlog.com/view/LMS-627)
Ensure that there are existing Learning Paths in the db.
1. Login as a trainer
2. Go to `http://localhost:3000/trainer/learning-paths/1`
3. Click on `Learners` tab
4. Click on `Add Learner` button to show Add Learner modal
5. Enter anything on the search bar and hit enter
6. Select trainees to be added
7. Click on `Add Learners` button
BE
- Learning path serializer
- Trainee view
FE
- services/learningPathAPI.ts
- services/traineeAPI.ts
- src/shared/components/Modal/AddLearnerModal.tsx
- Included fix for Add Learning Path bug
[Screencast 2023-06-13 09-47-42.webm](https://github.com/framgia/sph-lms/assets/116238730/85d8827d-3927-4bd3-b3aa-0e4cfb3b4688)
=> [LMS-627] [API/Integration] Learning Path Search and Add Learners

client/src/pages/trainer/dashboard/index.tsx, client/src/sections/dashboard/LearninPathSection.tsx, client/src/shared/components/Card/DashboardCard/index.tsx
https://framgiaph.backlog.com/board/LMS?selectedIssueKey=LMS-661&milestone=264153&assignee=417519
Display List of Learning Paths
Docker-compose up
Component/Card/DashboardCard/
pages/trainer/dashboard/index.tsx
LearningPath Section
Created  a new Dashboard Card Component
=> [LMS-661] [MARKUP] My Learning Paths tab

api/app_sph_lms/api/serializer/trainer_serializer.py, api/app_sph_lms/api/urls.py, api/app_sph_lms/api/view/course_view.py, api/app_sph_lms/api/view/trainee_view.py, client/src/pages/trainer/trainees/index.tsx, client/src/services/traineeAPI.ts, client/src/shared/components/Table/ListItem.tsx
https://framgiaph.backlog.com/view/LMS-665
Go to `localhost:3000/trainer/trainees`
- Trainee List Page
- Trainee API
- List Item
- Added hover effect for clickable rows
[Trainee List.webm](https://github.com/framgia/sph-lms/assets/111732984/158eb54b-2a74-49a4-bcd7-085382dfae71)
=> [LMS-665] [API/Integration] Trainee List page

api/app_sph_lms/api/serializer/trainer_serializer.py, api/app_sph_lms/api/urls.py, api/app_sph_lms/api/view/trainer_view.py, client/src/features/trainer/trainerCourseSlice.ts, client/src/redux/store.ts, client/src/sections/dashboard/CoursesSection.tsx, client/src/services/trainerAPI.ts, client/src/shared/utils/interface.ts
[LMS-658 [API/Integration] My Course tab](https://framgiaph.backlog.com/view/LMS-658)
Ensure you have existing courses in the db with the current user as the author.
1. Login as trainer
2. Go to `http://localhost:3000/trainer/dashboard`
3. Click on `My Courses` tab
BE
- urls
- trainer_serializer
FE
- store
- shared/utils/interfaces
- sections/dashboard/CoursesSection
n/a
[Screencast 2023-06-19 14-10-21.webm](https://github.com/framgia/sph-lms/assets/116238730/e939f00d-a9cf-45d3-be1b-bfbebe6886d9)
=> [LMS-658] [API/Integration] My Course tab

client/src/pages/trainee/dashboard/index.tsx, client/src/sections/dashboard/trainee/CoursesSection.tsx, client/src/shared/components/Card/TraineeCourseCard/index.tsx, client/src/shared/icons/ChevronRightIcon.tsx
https://framgiaph.backlog.com/view/LMS-681
Go to `localhost:3000/trainee/dashboard`
- Trainee Dashboard page
n/a
=> [LMS-681] [MARKUP] [Trainee] My Course Tab

client/src/middleware.ts, client/src/pages/trainee/dashboard/index.tsx, client/src/pages/trainer/dashboard/index.tsx, client/src/shared/components/Navbar/index.tsx, client/src/shared/utils/helpers.ts, client/src/shared/utils/interface.ts, client/src/types/next-auth.d.ts
https://framgiaph.backlog.com/view/LMS-686
https://github.com/framgia/sph-lms/assets/110364690/167c58b5-7f73-41b3-8bc3-40fb031ef5f2
=> LMS-686 - Restrict users from visiting unauthorized pages on FE and update navbar based on the user role

client/src/pages/trainee/dashboard/index.tsx, client/src/sections/trainee/MyLearningPathSection/index.tsx, client/src/shared/components/Card/LearningPathCard/index.tsx, client/src/shared/components/Tabs/index.tsx, client/src/shared/utils/interface.ts
https://framgiaph.backlog.com/view/LMS-682
It should have the following:
Redirect to http://localhost:3000/trainee/dashboard
Then in My Learning Paths Tab
client/src/pages/trainee/dashboard/index.tsx
client/src/sections/trainee/MyLearningPathSection/index.tsx
client/src/shared/components/Tabs/index.tsx
Delete static data after integration.
=> [LMS-682][MARKUP] My Learning Paths Tab

client/src/pages/404.tsx, client/src/pages/500.tsx, client/src/pages/error.tsx, client/src/pages/trainer/courses/[id]/index.tsx, client/src/pages/trainer/learning-paths/[id]/index.tsx, client/src/shared/components/Card/TraineeCourseCard/index.tsx, client/src/shared/layouts/Error/index.tsx
https://framgiaph.backlog.com/view/LMS-677
Go to `localhost:3000/trainer/courses` or `localhost:3000/trainer/learning-paths`
- 404 Page
- Course detail page
- Learning path detail page
n/a
[LMS-677.webm](https://github.com/framgia/sph-lms/assets/111732984/a6c12a78-f159-4fd0-b34d-49394a8b9c1c)
=> [LMS-677] [BUGFIX] [Course & Learning Path Detail Page] Return 404 on non-existing ID

api/app_sph_lms/api/serializer/course_serializer.py, api/app_sph_lms/api/urls.py, api/app_sph_lms/api/view/course_view.py, client/src/sections/dashboard/trainee/CoursesSection.tsx, client/src/services/traineeAPI.ts, client/src/shared/components/Card/TraineeCourseCard/index.tsx, client/src/shared/utils/interface.ts
[LMS-683 [API / INTEGRATION] My Course Tab](https://framgiaph.backlog.com/view/LMS-683)	
- log in as trainee,
- My Course Tab should display data dynamically with search, sort, pagination
- api/app_sph_lms/api/serializer/course_serializer.py
- api/app_sph_lms/api/urls.py
- api/app_sph_lms/api/view/course_view.py
- client/src/redux/store.ts
- client/src/sections/dashboard/trainee/CoursesSection.tsx
- client/src/services/traineeAPI.ts
- client/src/shared/components/Card/TraineeCourseCard/index.tsx
- client/src/shared/utils/interface.ts
- to test the functionality with data, assign courses to a trainee manually in django admin panel
=> LMS-683 - [API / INTEGRATION] My Course Tab

api/app_sph_lms/api/serializer/learning_path_serializer.py, api/app_sph_lms/api/view/learning_path_view.py, client/src/features/learning-path/learningPathSlice.ts, client/src/sections/learning-paths/settingsSection/EditSettingsButton.tsx, client/src/sections/learning-paths/settingsSection/index.tsx, client/src/services/learningPathAPI.ts
https://framgiaph.backlog.com/view/LMS-636
`docker exec -it lms-django bash`
`pipenv shell`
`pipenv run migrate`
api/app_sph_lms/admin.py
apilapp_sph_lms/api/serializer/learning_path serializer.py
api/app_sph_lms/api/urls.py
api/app_sph_lms/api/view/learning_path_view.py
api/app_sph_lms/migrations/0001_initial.py
api/app_sph_lms/migrations/0002_remove course status course_category_and more.py
api/app_sph_lms/migrations/0003_alter_lesson_link.py
api/app_sph_lms/migrations/0004 alter_lesson_order.py
api/app_sph_lms/migrations/0005 alter_lesson_order.py
api/app_sph_lms/migrations/0006_learningpath_rename_img_path_course_image_and_more.py
api/app_sph_lms/migrations/0007 alter_learningpath_author.py
api/app_sph_lms/models.py
client/features/learning-path/learningPathSlice.ts …
=> [LMS 636] - [API/ Integration] Settings tab in learning path detail page

client/src/sections/learning-paths/settingsSection/EditSettingsButton.tsx, client/src/shared/utils/interface.ts
[LMS-689 Fix build error](https://framgiaph.backlog.com/view/LMS-689)
- fix build error
run these commands:
`docker exec -it lms-nextjs sh`
`npm run build`
- it should build without error
- client/src/sections/learning-paths/settingsSection/EditSettingsButton.tsx
- client/src/shared/utils/interface.ts
n/a
=> LMS-689 Fix build error

api/app_sph_lms/api/serializer/course_serializer.py
[LMS-690 [Course Detail Page] [Settings Tab] Description Not Updating](https://framgiaph.backlog.com/view/LMS-690)
- Description should also update in course detail update
- go to course detail page (any course)
- browse to settings tab
- update course detail including the `description` 
- api/app_sph_lms/api/serializer/course_serializer.py
n/a
=> LMS-690 [Course Detail Page] [Settings Tab] Description Not Updating

client/src/pages/trainer/learning-paths/index.tsx, client/src/sections/learning-paths/ContentSection/index.tsx, client/src/sections/learning-paths/create/CourseItem.tsx, client/src/shared/components/Modal/AddLearnerModal.tsx
https://framgiaph.backlog.com/view/LMS-715
- Learning Path page
- Learning Path ContentSection
- AddLearnerModal
- CourseItem
n/a
=> [LMS-715] [BUGFIX] Fix build, button, & drag icon on learning path create

api/app_sph_lms/api/view/auth_view.py
[LMS-703 [DevServer] Authentication issues](https://framgiaph.backlog.com/view/LMS-703)
- can login using  allowed user
- visit https://sph-lms.vercel.app
- login
- in sign in prompt, use this temporary credential username = `admin` & passowrd = `password`
- auth_view.py
- this is not a solution but a bypass, the actual solution is for improvement. We will be needing the changes in this PR to login in backend so that we can proceed to UAT.
Basically, the changes is for UAT purposes only, and the fix for the issue will be included for improvements.
n/a
=> [DevServer] Authentication Issues

client/package-lock.json, client/package.json, client/src/pages/trainee/course/[id]/index.tsx
https://framgiaph.backlog.com/view/LMS-710
Course details should displayed these following :
`docker exec -it lms-nextjs sh`
`npm install`
Redirect here: `http://localhost:3000/trainee/course/1`
client/package-lock.json
client/package.json
client/src/pages/trainee/course/[id]/index.tsx
=> [LMS-710][MARKUP] Course View (overview)

api/app_sph_lms/api/serializer/course_serializer.py, api/app_sph_lms/api/view/course_view.py, client/src/pages/trainee/course/[id]/index.tsx, client/src/sections/dashboard/trainee/CoursesSection.tsx, client/src/services/traineeAPI.ts, client/src/shared/utils/interface.ts
https://framgiaph.backlog.com/view/LMS-712
1. Ensure that your trainee account is enrolled in a course
2. Go to http://localhost:3000/trainee/dashboard and click on any of the course cards
3. Click on Start/Continue course button (it should redirect to 404 page)
BE
- course serializer
- course view
FE
- pages/trainee/course/id
- sections/dashboard/trainee
- services/traineeAPI
- shared/utils.interface
n/a
[Screencast 2023-07-24 15-56-56.webm](https://github.com/framgia/sph-lms/assets/116238730/b5d2d769-6471-47e7-9a46-66aee6537eab)
=> [LMS-712] [API/Integration] Course View (overview)

api/app_sph_lms/apps.py, api/app_sph_lms/signals.py
[LMS-703 [DevServer] Authentication issues](https://framgiaph.backlog.com/view/LMS-703)
- make default password = "password" for newly registered account
- api/app_sph_lms/apps.py
- this will allow user to login in prompt using their email and password as "password" 
n/a
=> LMS-703 [DevServer] Authentication issues V2
