framgia/sph-lms

- client/src/pages/demo/components/index.tsx
- client/src/shared/components/Breadcrumbs/index.tsx
- [LMS-312](https://framgiaph.backlog.com/view/LMS-312)
- Able to show breadcrumbs depending on the url path
- create page/pages and import Breadcrumbs
- Example Links here
-http://localhost:3000/demo/components#breadcrumbs
n/a
- I base the breadcrumbs in NextJS route structure, assuming that we use the proper routing, the breadcrumbs will be fine
> [Reusable Component] Breadcrumbs

- client/src/pages/demo/layouts/tabs.tsx
- client/src/shared/layouts/tabs.tsx
[LMS-313](https://framgiaph.backlog.com/view/LMS-313)
> Able to create tabs  based on the figma layout
> When tabs are clicked, contents of each tabs are displayed.
cd client, npm run dev 
test: http://localhost:3000/demo/layouts/tabs
layout location: shared/layouts/tabs.tsx
n/a
n/a
> [NAVIGATION] Tabs

- client/src/shared/components/Dropdown/index.tsx
- client/src/shared/hooks/useOutsideClick.tsx
[LMS-331](https://framgiaph.backlog.com/view/LMS-331)
- useOutsideClick.tsx should be stored under src/shared/hooks
- Dropdown should implement the useEffect hook so that whenever users click outside the component it will trigger the component's state to close
1. cd client
2. npm run dev
- http://localhost:3000/demo/components#dropdown
n/a
Problem:
- There is no className prop in the component so when applied to the navbar, the border is still visible and there is no option to update it
- No useEffect in the dropdown component, the user still needs to click the component again to set the state to close
Solution:
- I added className as an optional prop so that when the dropdown component is implemented, the dev will have an option to add tailwindcss classes
- Applied …
> [LMS-331][Bug Fix] Fixed Dropdown Issue

- api/app/settings.py
- api/app_sph_lms/api/serializers.py
- api/app_sph_lms/api/views.py
- client/src/apis/index.ts
- client/src/pages/_app.tsx
- client/src/pages/auth/sign-in/index.tsx
- client/src/pages/home/index.tsx
- client/src/pages/trainer/courses/list/index.tsx
- client/src/shared/components/Avatar/index.tsx
- client/src/shared/components/Dropdown/index.tsx
- client/src/shared/components/Navbar/index.tsx
- client/src/shared/hooks/useAuthMiddleware.ts
- client/src/shared/hooks/useAuthSignIn.ts
- client/src/shared/hooks/useCreateCourse.ts
- client/src/shared/hooks/useFilterCourse.tsx
- client/src/shared/hooks/useSearchCourse.ts
- client/src/shared/hooks/useShowPerPage.ts
- client/src/shared/hooks/useSortByCourse.ts
- client/src/shared/utils/auth.ts
[LMS-347 [Integration] Sign-in Page](https://framgiaph.backlog.com/view/LMS-347)
Follow the step to reproduce of the new migration file:
[Reference](https://github.com/framgia/sph-lms/pull/55)
Got to [Sign In Page](http://localhost:3000/auth/sign-in)
- Creds
-- admin@gmail.com
-- password
- access landing page manually (should return to /home)
- access sign in page manually (should return to /home)
n/a
- /home page has hydration error which is not a part of my task, just close the error modal adn test features of my task only
> [LMS-347][Integration] Sign In page

- client/src/pages/demo/components/index.tsx
- client/src/pages/users/[company_id]/list/index.tsx
- client/src/shared/components/Button/index.tsx
- client/src/shared/components/InputField/index.tsx
- client/src/shared/components/Modal/Modal.tsx
- client/src/shared/hooks/useEditAddUser.ts
- client/src/shared/icons/EditIcon.tsx
- client/src/shared/icons/XmarkIcon.tsx
https://framgiaph.backlog.com/board/LMS?selectedIssueKey=LMS-354
Be able to create a reusable modal for add and edit user
cd client
npm run dev
visit url: http://localhost:3000/users/3/list
Select, Input Field,  User's List Page, Modal Component
* I added small changes to the style of input field component so that it will be same to the select component 
* I only put "All fields should be required" and "Password Do not match" validation message since it will be replaced with BE Validations
*outside click function will set aside first need to do bugfix in the useOutsideClick later
> [LMS-354][FE][Markup][Reusable] Add Modal & Edit Modal

- client/package-lock.json
- client/package.json
- client/src/pages/auth/sign-in/index.tsx
- client/src/pages/classes/[company_id]/list/index.tsx
- client/src/pages/demo/components/index.tsx
- client/src/sections/classes/AddClassModal.tsx
- client/src/shared/components/Button/index.tsx
- client/src/shared/components/ReactForm/RFInputField/index.tsx
- client/src/shared/hooks/useAuthSignIn.ts
- client/src/shared/utils/interface.ts
[LMS-366 [Refactor][FE][Class List][Add Class Button]](https://framgiaph.backlog.com/view/LMS-366)
- Visit these pages and do necessary QA testing
-- http://localhost:3000/demo/components
-- http://localhost:3000/classes/1/list
-- http://localhost:3000/auth/sign-in
- client/src/pages/auth/sign-in/index.tsx
- client/src/pages/demo/components/index.tsx
- client/src/shared/components/Button/index.tsx
- client/src/shared/hooks/useAuthSignIn.ts
- so far, authentication, create course, create company user, and add class are the only ones that needs Form,
- Authentication and Add Class are both using React Hook Form
- I already informed dev that handles Create Company User to align the code to my refactored code
- Create Course needs total refactor and has its own task, ill …
> [LMS-366][Refactor][FE] Class List Add Button

- api/app_sph_lms/api/serializers.py
- api/app_sph_lms/api/views.py
[LMS-363](https://framgiaph.backlog.com/view/LMS-363)
List Filters:
1. Add another course using the django admin panel
2. To set the category of the created course. Go to CourseCategory in admin panel, then select the created course as well as the category you want the course to have
3. Login in using postman with proper credentials to gain access token
4. Add auth token
5. Access this GET API: localhost:8000/api/course
6. Try the filter parameters provided below this instructions. There is also an example endpoint for your convenience. 
Filter params:
name: <Course Name>
sort: name_asc || name_desc
status: active || inactive
category: <Course ID> in csv format
Example using the params
localhost:8000/api/course?status=active&name=Course 1&sort=name_asc&category=1,2
Serializer
Views
_will …
> [LMS-363][BUG FIX] Course List Filter

- api/app_sph_lms/api/views.py
- client/src/pages/classes/[company_id]/list/index.tsx
- client/src/shared/hooks/useShowClassList.ts
[LMS-368](https://framgiaph.backlog.com/view/LMS-368)
http://localhost:3000/classes/1/list
For the postman:
localhost:8000/api/classes/1?page_size='number per page'&page='page number'
api/app_sph_lms/api/serializers.py
api/app_sph_lms/api/views.py
client/src/pages/classes/[company_id]/list/index.tsx
client/src/shared/hooks/useShowClassList.ts
- I created another fetching on the useEffect to fetch all the classesto be used in the 'Showing 1 to 10 of 20 entries part'  since the first fetching only fetched the data per page and page_size. I just used a flag to avoid calling the API again.
> [LMS-368][Integration]Class List, Pagination

- client/src/pages/element/material/index.tsx
- client/src/sections/users/usersUpdateDelete.tsx
- client/src/shared/components/Dropdown/index.tsx
- client/src/shared/components/SearchBar/SearchBar.tsx
- client/src/shared/components/Select/index.tsx
- client/src/shared/components/Table/HeaderTitle.tsx
- client/src/shared/components/Table/Icon.tsx
- client/src/shared/components/Table/ListItem.tsx
- client/src/shared/components/Table/index.tsx
- client/src/shared/icons/EditIcon.tsx
- client/src/shared/icons/FileIcon.tsx
- client/src/shared/icons/FolderIcon.tsx
- client/src/shared/icons/LinkIcon.tsx
- client/src/shared/icons/TrashIcon.tsx
- client/src/shared/icons/VideoIcon.tsx
- client/src/shared/utils/navBarList.ts
Issue: https://framgiaph.backlog.com/view/LMS-378
- Visit `/element/material` page
- client/src/shared/components/Dropdown/index.tsx
- client/src/shared/components/SearchBar/SearchBar.tsx
- client/src/shared/components/Select/index.tsx
- client/src/shared/components/Table/index.tsx
- client/src/shared/icons/EditIcon.tsx
- client/src/shared/icons/TrashIcon.tsx
- client/src/shared/utils/navBarList.ts
n/a
https://user-images.githubusercontent.com/110364690/234811619-30b23ba3-2379-448e-babd-16d9475e8d77.mp4
> LMS-378 - [FE] Material List, Search, Buttons

- client/src/pages/trainer/learning-paths/[id]/index.tsx
- client/src/sections/learning-paths/ContentSection/index.tsx
- client/src/sections/learning-paths/create/PreviewSection.tsx
- client/src/shared/components/Card/CourseCard/index.tsx
- client/src/shared/components/Card/LearningPathCourseCard/index.tsx
https://framgiaph.backlog.com/view/LMS-634
Go to `http://localhost:3000/trainer/learning-paths/1` [Content Tab]
n/a
n/a
> [LMS-634] [Markup] [Content Tab] Trainer can visit content tab in learning path detail page

- api/app_sph_lms/api/serializer/course_serializer.py
- client/features/course/learnerSlice.ts
- client/services/traineeAPI.ts
- client/src/sections/courses/LearningSection/index.tsx
- client/src/shared/components/Dropdown/index.tsx
[LMS-610 [API/ Integration] [Learners tab] Sorting learners](https://framgiaph.backlog.com/view/LMS-610)
Create an api for filtering learners that is associated with the course in course detail page
- Can be sorted in Alphabetically (asc or desc)
- Removed sorting on progress sicne it is moved to next phase
1. go to `http://localhost:3000/trainer/courses`
2. select any courses
3. if there is no learners, add learners
4. sort learners
`http://[localhost:3000/trainer/courses/1](http://localhost:3000/trainer/courses/COURSE_ID)`
n/a
> LMS-610 [API/ Integration] [Learners tab] Sorting learners

- client/features/learning-path/learningPathSlice.ts
- client/features/tab/tabSlice.ts
- client/src/pages/trainer/courses/index.tsx
- client/src/pages/trainer/learning-paths/[id]/index.tsx
- client/src/sections/courses/SettingsSection/index.tsx
- client/src/sections/courses/create/AddLessonSection.tsx
- client/src/sections/learning-paths/create/AddCourseSection.tsx
- client/src/sections/learning-paths/create/CourseItem.tsx
- client/src/sections/learning-paths/create/InitialSection.tsx
- client/src/sections/learning-paths/settingsSection/EditSettingsButton.tsx
- client/src/sections/learning-paths/settingsSection/index.tsx
- client/src/shared/components/Button/EditModeButtons.tsx
- client/src/shared/components/Card/CourseCard/index.tsx
- client/src/shared/components/Collapse/Collapse.tsx
- client/src/shared/components/Modal/ConfirmationModal.tsx
- client/src/shared/components/Modal/Modal.tsx
- client/src/shared/components/Tabs/index.tsx
https://framgiaph.backlog.com/view/LMS-632
- have edit setting button that allows trainer to edit context of learning path
- have inputs for name and description
- display list of courses  
- display toggle icon and expand course on click
- display archive button
- display add course button
- toggle edit mode
- have a modal for adding new course in a learning path based on the figma design
The modal should display:
- Filter button
- Search bar
- List of courses (static)
- Pagination
- Cancel and add course buttons
- client/features/learning-path/learningPathSlice.ts
- client/features/tab/tabSlice.ts
- client/src/pages/trainer/courses/index.tsx
- client/src/pages/trainer/learning-paths/[id]/index.tsx
- client/src/sections/courses/SettingsSection/EditSettingsButton.tsx
- …
> LMS-632 - [Markup] [Settings tab] Display settings tab in learning path detail page

- client/src/sections/courses/create/LessonItem.tsx
- client/src/sections/learning-paths/ContentSection/index.tsx
- client/src/sections/learning-paths/create/CourseItem.tsx
- client/src/shared/components/Card/CourseCard/index.tsx
- client/src/shared/components/Card/LearningPathCard/index.tsx
- client/src/shared/components/Card/LearningPathCourseCard/index.tsx
https://framgiaph.backlog.com/view/LMS-645
Go to `http://localhost:3000/trainer/courses`
Go to course detail settings
- Courses page
- Learning Paths page
- Lesson Item
- Course Card
- Learning Path Card
n/a
Course Card
Learning Path Card
View mode
Edit mode
> [LMS-645] [BUGFIX] CourseCard Components & Lesson Item Component Fixes

- api/app_sph_lms/api/serializer/learning_path_serializer.py
- client/services/learningPathAPI.ts
- client/src/pages/trainer/learning-paths/index.tsx
- client/src/sections/learning-paths/index.tsx
[LMS-624 [API/Integration] Trainer can search learning path](https://framgiaph.backlog.com/view/LMS-624)
1. Login as trainer
2. Go to `http://localhost:3000/trainer/learning-paths`
3. Input in the search bar and hit enter
BE
- Learning path serializer
FE
- Learning Paths Page
- Included fix for Add Learning Path bug
- Updated `client/services/learningPathAPI` to include `Tags` for fetching of newly created LPs
[Screencast 2023-06-09 11-20-44.webm](https://github.com/framgia/sph-lms/assets/116238730/e06421c5-b15f-43d4-bf6a-5adaea997f25)
> [LMS-624] [API/Integration] Trainer can search learning path

- client/src/pages/_document.tsx
- client/src/pages/trainer/dashboard/index.tsx
- client/src/shared/utils/navBarList.ts
- client/styles/globals.css
- client/tailwind.config.js
[LMS-650 [Markup] Trainer Dashboard](https://framgiaph.backlog.com/view/LMS-650)
1. Login as trainer
2. Go to `http://localhost:3000/trainer/dashboard`
- Navbar list
- globals.css
- Tailwind config
- Added Lora and Inter fonts
> [LMS-650] [Markup] Trainer Dashboard

- client/features/learning-path/learnerSlice.ts
- client/src/sections/courses/LearningSection/index.tsx
- client/src/sections/learning-paths/LearnersSection/index.tsx
https://framgiaph.backlog.com/board/LMS?selectedIssueKey=LMS-646&assignee=417519
docker-compose up
visit url: http://[localhost:3000/trainer/courses/3](http://localhost:3000/trainer/courses/3)
http://[localhost:3000/trainer/learning-paths/3](http://localhost:3000/trainer/learning-paths/3)
sections/courses/LearningSection/index.tsx
sections/learning-paths/LearningSection.tsx
Use the SortDropdown component instead of dropdown component for both course and learning paths learner section  [pls comment if I should delete the other 1]
> [LMS-646] Learners Tab (Course & Learning Path) adjustments

- api/app_sph_lms/api/serializer/learning_path_serializer.py
- client/src/sections/learning-paths/LearnersSection/index.tsx
- client/src/services/traineeAPI.ts
[LMS-628 [API/Integration] Learning Path Detail - Sort Learners in Learners Tab](https://framgiaph.backlog.com/view/LMS-628)
Ensure that you have existing Learning Paths and Users (trainees) in the db
1. Go to `http://localhost:3000/trainer/learning-paths/1`.
2. Click on Learners tab.
3. If there are no learners yet, add more than one.
4. Click on the Sort button.
BE
- Learning Path serializer
- Trainee view
FE
- `traineeAPI` service
- Learning Path Detail - Learners Tab
n/a
> [LMS 628] [API/Integration] Learning Path Detail - Sort Learners in Learners Tab

- api/app_sph_lms/api/serializer/trainer_serializer.py
- api/app_sph_lms/api/urls.py
- api/app_sph_lms/api/view/trainer_view.py
- client/src/features/trainer/trainerLearningPathSlice.ts
- client/src/pages/trainer/learning-paths/create/index.tsx
- client/src/redux/store.ts
- client/src/sections/dashboard/LearningPathSection.tsx
- client/src/services/trainerAPI.ts
- client/src/shared/components/Tabs/index.tsx
- client/src/shared/utils/interface.ts
https://framgiaph.backlog.com/view/LMS-662
Go to `localhost:3000/trainer/dashboard`
Click the `My Learning Paths` tab
- `LearningPathSection`
- `Tabs`
- `store`
- **[FIXED]** Encountered a bug in the `Tabs` component where the `activeTab` is not reset when the page changes (See attachment below)
- Used `pageSize = 3` for demo purposes. Reverted back to `9` before commit
[LMS-662.webm](https://github.com/framgia/sph-lms/assets/111732984/6f343fe9-15ef-4155-9ec6-3889dbe0a337)
> [LMS-662] [API/Integration] My Learning Paths tab

- api/Dockerfile
- client/src/pages/trainee/dashboard/index.tsx
- client/src/pages/trainer/dashboard/index.tsx
- client/src/shared/utils/interface.ts
https://framgiaph.backlog.com/board/LMS?selectedIssueKey=LMS-680&assignee=417519
Create the trainee dashboard in /trainee/dashboard including the tabs.
Tabs can have a simple message like tab1, tab2
`docker-compose up`
visit url:[ http://[localhost:3000/trainee/dashboard
](http://localhost:3000/trainee/dashboard)
pages/trainee/dashboard/index.tsx
> [LMS-680][MARKUP] Trainee Dashboard

- client/src/sections/courses/ContentSection.tsx
- client/src/shared/components/Iframe/index.tsx
- client/src/shared/components/SidebarContent/index.tsx
- client/src/shared/utils/helpers.ts
https://framgiaph.backlog.com/board/LMS?selectedIssueKey=LMS-674&assignee=417519
Fix content material width.
For rendering the content, we have 2 approach:
- if the link is youtube, display it in Iframe
- if the link is udemy, render a button instead to redirect in that link.
docker-compose up
Button Component
Course Detail Page
Sidebar Component
Create new course and add lesson link with youtube embed and add lesson with udemy link to test.
> [LMS-674][Course][Content Tab] Content Width and Lesson Link

- client/src/sections/courses/SettingsSection/index.tsx
- client/src/sections/courses/create/InitialSection.tsx
- client/src/sections/learning-paths/create/InitialSection.tsx
- client/src/shared/components/ReactForm/RFTextField/index.tsx
https://framgiaph.backlog.com/view/LMS-691
n/a
n/a
> [LMS-691] [BUGFIX] [Course & Learning Path] [Settings Tab] Update Description display and Delete Confirmation Should use Dynamic name

- api/app_sph_lms/api/serializer/learning_path_serializer.py
- api/app_sph_lms/api/view/learning_path_view.py
- client/src/sections/learning-paths/create/CourseItem.tsx
- client/src/shared/components/Collapse/Collapse.tsx
https://framgiaph.backlog.com/view/LMS-692
Go to `http://localhost:3000/trainer/learning-paths/1`
Click on `Content` tab to check the order of courses
Click on `Settings` tab and toggle between edit and view mode to check the visibility of the drag icon
BE
- Learning Path serializer
- Learning Path view
FE
- client/src/sections/learning-paths/create/CourseItem.tsx
- client/src/shared/components/Collapse/Collapse.tsx
n/a
> [LMS-692] [BUGFIX] [Learning Path Detail Page] Display courses by order & hide drag icon on non-edit mode

- client/src/pages/trainer/courses/index.tsx
- client/src/sections/courses/LearningSection/index.tsx
- client/src/sections/learning-paths/LearnersSection/index.tsx
- client/src/shared/components/Button/EditModeButtons.tsx
https://framgiaph.backlog.com/view/LMS-693
[x] - Every buttons uses almost the same styles
Redirect to the following to see the buttons:
- http://localhost:3000/trainer/courses - Create a course button
- http://localhost:3000/trainer/courses/2 - Learners tab and Settings tab
- http://localhost:3000/trainer/learning-paths - Create learning path button
- http://localhost:3000/trainer/learning-paths/2 - Learning tab and Settings tab
client/src/pages/trainer/courses/index.tsx
client/src/sections/courses/LearningSection/index.tsx
client/src/sections/learning-paths/LearnersSection/index.tsx
client/src/shared/components/Button/EditModeButtons.tsx
> [LMS-693]-[Bugfix] Make Button Style Uniform

- client/src/sections/learning-paths/ContentSection/index.tsx
- client/src/shared/components/Card/LearningPathCourseCard/index.tsx
https://framgiaph.backlog.com/view/LMS-701
redirect to: http://localhost:3000/trainer/learning-paths/2
client/src/sections/learning-paths/ContentSection/index.tsx
client/src/shared/components/Card/LearningPathCourseCard/index.tsx
Since we have replaced the design Learning path data is already integrated. I only edited some of the UI changes.
> [LMS-701][MARKUP] Refactor Learning Path Design

- client/src/sections/learning-paths/ContentSection/index.tsx
https://framgiaph.backlog.com/board/LMS?selectedIssueKey=LMS-702&assignee=417519
`docker-compose up`
contentSection
Go to Learning Path Detail and check integration functionality
> [LMS-702][API/INTEGRATION] Update API response and integration

- client/src/pages/trainer/courses/index.tsx
- client/src/pages/trainer/learning-paths/index.tsx
https://framgiaph.backlog.com/view/LMS-707
Redirect to:
Courses tab: http://localhost:3000/trainer/courses
Learning Path tab: http://localhost:3000/trainer/learning-paths
Click active and inactive, with and without learning path data.
client/src/pages/trainer/courses/index.tsx
client/src/pages/trainer/learning-paths/index.tsx
client/src/shared/components/Tabs/Tab.tsx
[lms-707.webm](https://github.com/framgia/sph-lms/assets/110363852/6fdcd123-7c02-4915-b6ad-85b4708b596d)
> [LMS-707][MARKUP] Course & Learning Path List Page

- client/src/pages/trainee/course/[id]/training/index.tsx
- client/src/sections/courses/ContentSection.tsx
- client/src/shared/components/SidebarContent/index.tsx
https://framgiaph.backlog.com/board/LMS?selectedIssueKey=LMS-711&assignee=417519
create training page
2 sections, left section list down the lessons and its status (checkbox), right section shows content. (Use same implementation used in trainer's course content tab)
selecting lessons should update content
docker-compose up
visit url: http://localhost:3000/trainee/course/1/training
sidebarContent Component
training page
test markup for training page
Checkbox should be functioning
should not set to active tab when checkbox is clicked
Implemented same design to trainer's course content page
> [LMS-711][MARKUP] Create Training Page

- api/app_sph_lms/api/serializer/completed_lesson_serializer.py
- api/app_sph_lms/api/urls.py
- api/app_sph_lms/api/view/completed_lesson_views.py
- client/src/pages/trainee/course/[id]/training/index.tsx
- client/src/services/traineeAPI.ts
- client/src/shared/components/SidebarContent/SideBar.tsx
- client/src/shared/components/SidebarContent/index.tsx
- client/src/shared/utils/interface.ts
[LMS-713 [API/INTEGRATION] Training Page](https://framgiaph.backlog.com/view/LMS-713)
- create api for creating and updating completed lessons
- change the static display to dynamic data (use the api that will be used in [API/INTEGRATION] Course View (overview) task)
- checkbox onclick should trigger an API to update/create completed lessons
- go to http://localhost:3000/trainee/course/<:id>
- it should display dynamic data
- checkbox should trigger create and delte completed lesson
- api/app_sph_lms/api/urls.py
- client/src/pages/trainee/course/[id]/training/index.tsx
- client/src/services/traineeAPI.ts
- client/src/shared/components/SidebarContent/SideBar.tsx
- client/src/shared/components/SidebarContent/index.tsx
- client/src/shared/utils/interface.ts
n/a
> LMS-713 [API/INTEGRATION] Training Page

- client/src/pages/trainee/course/[id]/index.tsx
- client/src/pages/trainee/learning-path/[id]/index.tsx
- client/src/sections/learning-paths/ContentSection/index.tsx
- client/src/services/traineeAPI.ts
- client/src/shared/components/Card/LearningPathCard/index.tsx
[LMS-714 [MARKUP/INTEGRATION] Trainee Learning Path Page](https://framgiaph.backlog.com/view/LMS-714)
- reuse the existing Learning path page sections in trainers side
- make sure that the go to course button redirects to tranee's url path (update the redirect depends on role)
- for course content details, under course overview, the lessons should display the status (checkbox)
- in dashboard, toggle to `My Leaning Path` and click enrolled learning path ( for testing purposes you can add manually in django admin panel)
- client/src/pages/trainee/course/[id]/index.tsx
- client/src/sections/learning-paths/ContentSection/index.tsx
- client/src/services/traineeAPI.ts
- client/src/shared/components/Card/LearningPathCard/index.tsx
n/a
> LMS-714 [MARKUP/INTEGRATION] Trainee Learning Path Page

- api/app_sph_lms/signals.py
- client/src/pages/index.tsx
[LMS-716 Fix Index Page Redirection](https://framgiaph.backlog.com/view/LMS-716)
- index page redirects to user's dashboard
- visit http://localhost:3000
- you will be redirected to user's dashboard or sign in page
- api/app_sph_lms/signals.py
- client/src/pages/index.tsx
- I also included minimal additional settings for signals.py
> LMS-716 Fix Index Page Redirection
